### ISSUE TITLE
New Discord update broke the script

### ISSUE THREAD

**Issue by EngineExt** [riolubruh/DiscordFreeStickers#4]
**Describe the bug**
New Discord update broke the script

**To Reproduce**
- Update discord

- Update discord
- Enable plugin

**Expected behavior**
Script starting and working

**log**
```
    Error: Couldn't find PermissionEvaluator
    at findModules (FreeStickers.plugin.js:3711:39)
    at Object.Start [as start] (FreeStickers.plugin.js:3720:5)
    at N.startPlugin (renderer.js:5:29059)
    at N.startAddon (renderer.js:5:28852)
    at N.enableAddon (renderer.js:5:7535)
    at N.toggleAddon (renderer.js:5:8334)
    at N.togglePlugin (renderer.js:5:26140)
    at renderer.js:5:92556
    at renderer.js:5:124717
    at Object.eF (67096.60fb03d0b62c1fe1124f.js:12:930190)
    at eG (67096.60fb03d0b62c1fe1124f.js:12:930344)
    at 67096.60fb03d0b62c1fe1124f.js:12:948653
    at re (67096.60fb03d0b62c1fe1124f.js:12:948752)
    at rt (67096.60fb03d0b62c1fe1124f.js:12:949166)
    at 67096.60fb03d0b62c1fe1124f.js:12:954628
    at sA (67096.60fb03d0b62c1fe1124f.js:12:1011701)
    at eI (67096.60fb03d0b62c1fe1124f.js:12:929328)
    at rs (67096.60fb03d0b62c1fe1124f.js:12:950457)
    at tF (67096.60fb03d0b62c1fe1124f.js:12:936125)
    at tP (67096.60fb03d0b62c1fe1124f.js:12:935909)
```

**Client:**
Desktop [Windows 10 64-Bit (10.0.19045)]
Stable 303105 (1897d8a)
Plugin Version [1.4.3]
BD Version [1.10.2]

**Comment by riolubruh** [comment]
Fixed in 1.4.4 7a6ca68
